networks:
  network_example:
    driver: bridge

services:
  myapp:
    build:
      dockerfile: 'Dockerfile'
    container_name: myapp-example
    depends_on:
      - mongodb-example
    ports:
      - "8080:8080"
    networks:
      - network_example

  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: myuser
      MONGO_INITDB_DATABASE: myuser
    networks:
      - network_example

